name: po_contacts_flutter
description: The PO contacts app built with flutter.
version: 2.1.0+55

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common - pure dart
  pointycastle: 1.0.2
  http: ^0.12.1
  crypto: ^2.1.4
  uuid: ^2.1.0
  image: ^2.1.12

  # Common - flutter
  google_sign_in: ^4.4.6
  draggable_scrollbar: ^0.0.4
  shared_preferences: ^0.5.6+3

  # Flutter - Mobile only
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  sqflite:
  path_provider: ^1.5.1
  image_picker: ^0.6.3+1
  flutter_secure_storage: ^3.3.3

  # Flutter - Web only
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/app_icon.png
    - lib/assets/images/ic_profile.png
