name: po_contacts_flutter
description: The PO contacts app built with flutter.
version: 1.2.0+31

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common - pure dart
  pointycastle: 1.0.2

  # Common - flutter
  google_sign_in: ^4.4.6
  draggable_scrollbar: ^0.0.4
  shared_preferences: ^0.5.6+3

  # Flutter - Mobile only
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  sqflite:
  path_provider: ^1.5.1
  image_picker: ^0.6.3+1

  # Flutter - Web only
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/ic_profile.png
