name: po_contacts_flutter
description: The PO contacts app built with flutter.
version: 2.2.0+61

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common - pure dart
  pointycastle: ^3.0.0-nullsafety.2
  http: ^0.13.0
  crypto: ^3.0.0
  uuid: ^3.0.1
  image: ^3.0.1

  # Common - flutter
  google_sign_in: ^5.0.0
  # TODO draggable_scrollbar
  # draggable_scrollbar: ^0.0.4
  shared_preferences: ^2.0.4
  convert: ^3.0.0

  # Flutter - Mobile only
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.2
  sqflite: ^2.0.0+2
  path_provider: ^2.0.1
  image_picker: ^0.7.2+1
  flutter_secure_storage: ^4.1.0

  # Flutter - Web only
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/app_icon.png
    - lib/assets/images/ic_profile.png
