name: po_contacts_flutter
description: The PO contacts app built with flutter.
version: 2.2.1+63

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common - pure dart
  pointycastle: ^3.7.3
  http: ^1.1.0
  crypto: ^3.0.3
  uuid: ^3.0.7
  image: ^4.0.17

  # Common - flutter
  google_sign_in: ^6.1.4
  draggable_scrollbar: ^0.1.0
  shared_preferences: ^2.2.0

  # Flutter - Mobile only
  url_launcher: ^6.1.12
  sqflite:
  path_provider: ^2.1.0
  image_picker: ^1.0.2
  flutter_secure_storage: ^8.0.0

  # Flutter - Web only
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/app_icon.png
    - lib/assets/images/ic_profile.png
